### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by Jdegroot1** [HUSSBV/homey_nl.luxaflex.powerview#4]
Is this version working on homey 2.0?

**Comment by JasperHuijser** [comment]
Hi,
We have not been able to test it but feel free to do so yourself :)

**Comment by Redwood001** [comment]
Is version 0.012 working fine in Homey 2.0? 
When i upgrade Homey to 2.0 I can't go back to version 1.53
Luxaflex Powerview with (Gen 1) works fine in version 1.53!

**Comment by Jdegroot1** [comment]
Hi Jasper,

Works in 2.0. Thanks.

**Comment by JasperHuijser** [comment]
Thanks for the report!
